### ISSUE TITLE
Gitbitex NPM ERROR: Can't get it working on Windows

### ISSUE THREAD

**Issue by KabDeveloper** [gitbitex/gitbitex-web#4]
Hi,

I can't get it working on windows !

```
> gitbitex@1.0.0 start C:\Users\Dev\webexchange
> gulp

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\Dev\webexchange\node_modules\und
ertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\Dev\webexchange\node_modules\undertaker\lib\t
ask.js:13:8)
    at C:\Users\Dev\webexchange\gulpfile.js:59:25
    at createTask (C:\Users\Dev\webexchange\gulpfile.js:62:11)
    at Object.<anonymous> (C:\Users\Dev\Desktop\webexchange\gulpfile.js:178:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gitbitex@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gitbitex@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2020-06-26T18_16_26_44
3Z-debug.log
```

When I run NPM INSTALL

```
npm WARN using --force I sure hope you know what you are doing.
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but n
ed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.0 requires a peer of popper.js@^1.16.0 but
led. You must install peer dependencies yourself.
npm WARN gitbitex@1.0.0 No repository field.
npm WARN gitbitex@1.0.0 No license field.

audited 1390 packages in 36.603s
found 16 vulnerabilities (12 low, 2 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by SC4RECOIN** [comment]
this is an issue with gulp
downgrading to node10 should resolve the issue
